### ISSUE TITLE
No Browse button for file and also i had hide userId

### ISSUE THREAD

**Issue by aviral-92** [rinkuvatscs/interviewService#11]
![adduserdetails](https://cloud.githubusercontent.com/assets/17472010/14940251/d8e5416e-0f8b-11e6-9ee9-90e7add44eb8.PNG)

Hi Rinku,

see i had removed userId from addUserDetails service but i have seen 1 thing that u had enable file upload in that through browse button on friday. But it dosent seems over here when i take pull. Can you once see to it.

please find the attachment.

**Comment by rinkuvatscs** [comment]
Aviral u r searching in wrong file i have implemented file option in InterbViewServiceController not in UserDetailController . UserDetailController is only for user details that will not store file etc . File location etx will be stored using InterviewServiceController. InterviwServiceController Service will use userDetail classes for finding details

**Comment by aviral-92** [comment]
ohhhk i was taking it wrong :-p :+1:
