### ISSUE TITLE
State Service work completion

### ISSUE THREAD

**Issue by rinkuvatscs** [rinkuvatscs/interviewService#15]
Tasks :
1) Create 1 more Jsp File which have all the field which is going at a time of save so on the basis of that we will search in database and will show all then details related to video...
LIke i have added One video and FIrst Name is Rinku , Last Name Sharma , Location Noida , COuntry INdia , State UP , email rinkuvatscs@gmail.com , Mobile number 9759569142 and also provided VIdeo okies now i want to see my video so for seeing video there will be a jso named search.jsp in which there will be text boxes for searching first name , last name , email , mobile number , country , state , location so on the basis of data we will search in USER_DETAIL table as well as INTERVIEW_DETAIL table firstly we will check is user exist with that email id or not if exists then with the help of user_id we will show all then video details from INTERVIEW_DETAIL table

2) @aviral-92 Please complete state service work also ...

**Comment by aviral-92** [comment]
@rinkuvatscs  i am working on state Service and also implementing location and then will make jsp which u had mentioned.

**Comment by rinkuvatscs** [comment]
first task is creating JSP after that we will work on state service

**Comment by rinkuvatscs** [comment]
Just commit whatever u have completed for state service and start on jsp work ... okies i will start work on state service

**Comment by aviral-92** [comment]
i just added location in UserDetail as well as InterviewDetail service and was testing. i am going to commit that. State Service yet to start so instead of that i am working on Jsp.

**Comment by aviral-92** [comment]
1 more thing i want to modify my interview_details table and want to add foreign key in that for userid and add interviewId column in that so that the thing u want through jsp mentioned above will be achieve. shall i???

**Comment by rinkuvatscs** [comment]
Onlylocation field will be in INTERVIEW_DETAIL not in USER_DETAIL okies

**Comment by aviral-92** [comment]
hmm okk

Thanks
Aviral Mittal
