### ISSUE TITLE
Code Testing

### ISSUE THREAD

**Issue by rinkuvatscs** [rinkuvatscs/interviewService#8]
Hey Aviral And Goru ,

Before starting new services please test already created services properly and create text file for request so that i can perform code refactoring our today's goal to Run Topic and Country Service Properly . After that we will focus on UserDetail and Interview Service which is only pending to perform .

We have to Finish interviewService end of this week . I am working on other module i.e **'car-service'** after completing this service we will discuss over that service .

**Comment by aviral-92** [comment]
Hi Rinku,

I am working on InventoryService test plan and understanding that so that it can be implemented in our service. And at the end i will create text file for all request of my Service.

**Comment by rinkuvatscs** [comment]
Please try to finish it as soon as possible
